### ISSUE TITLE
Recovery?

### ISSUE THREAD

**Issue by notRuslan** [rubo77/mysql-backup.sh#1]
Do you have another script for recovery?
If recover MySQL server on new instance it takes a lot of time.

**Comment by rubo77** [comment]
I just usw the standard

```
 mysql $db < sqlfile.sql
```

**Comment by notRuslan** [comment]
These two tables gives error
cat  mysql.slow_log.sql | mysql -uroot  mysql
ERROR 1556 (HY000) at line 43: You can't use locks with log tables.
cat mysql.general_log.sql | mysql -uroot  mysql
ERROR 1556 (HY000) at line 38: You can't use locks with log tables.

I use similar method to:
for sql_file in `ls /path/to/directory/*.sql`; do echo $sql_file ; mysql -uUSER -pPASSWORD DATABASE < $sql_file ; done

Needs small script to take DB name from file for restore :)

**Comment by rubo77** [comment]
maybe you want to add a Pull Request to change the Readme accordingly?

**Comment by notRuslan** [comment]
No, Thanks.
I create my disaster recovery plan for MyISAM db , and checked some scripts yours looks better than others.  Thanks for your job.
